-- Index of the line in our grid for a specific trait
ECO = ECO or {}

ECO.Traits = {
	[ITEM_TRAIT_TYPE_WEAPON_POWERED] = 1,
	[ITEM_TRAIT_TYPE_WEAPON_CHARGED] = 2,
	[ITEM_TRAIT_TYPE_WEAPON_PRECISE] = 3,
	[ITEM_TRAIT_TYPE_WEAPON_INFUSED] = 4,
	[ITEM_TRAIT_TYPE_WEAPON_DEFENDING] = 5,
	[ITEM_TRAIT_TYPE_WEAPON_TRAINING] = 6,
	[ITEM_TRAIT_TYPE_WEAPON_SHARPENED] = 7,
	[ITEM_TRAIT_TYPE_WEAPON_DECISIVE] = 8,
	[ITEM_TRAIT_TYPE_WEAPON_NIRNHONED] = 9,
	[ITEM_TRAIT_TYPE_ARMOR_STURDY] = 10,
	[ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = 11,
	[ITEM_TRAIT_TYPE_ARMOR_REINFORCED] = 12,
	[ITEM_TRAIT_TYPE_ARMOR_WELL_FITTED] = 13,
	[ITEM_TRAIT_TYPE_ARMOR_TRAINING] = 14,
	[ITEM_TRAIT_TYPE_ARMOR_INFUSED] = 15,
	[ITEM_TRAIT_TYPE_ARMOR_PROSPEROUS] = 16,
	[ITEM_TRAIT_TYPE_ARMOR_DIVINES] = 17,
	[ITEM_TRAIT_TYPE_ARMOR_NIRNHONED] = 18,
}

ECO.styleChapters = {
	[1] = ITEM_STYLE_CHAPTER_AXES,
	[2] = ITEM_STYLE_CHAPTER_BELTS,
	[3] = ITEM_STYLE_CHAPTER_BOOTS,
	[4] = ITEM_STYLE_CHAPTER_BOWS,
	[5] = ITEM_STYLE_CHAPTER_CHESTS,
	[6] = ITEM_STYLE_CHAPTER_DAGGERS,
	[7] = ITEM_STYLE_CHAPTER_GLOVES,
	[8] = ITEM_STYLE_CHAPTER_HELMETS,
	[9] = ITEM_STYLE_CHAPTER_LEGS,
	[10] = ITEM_STYLE_CHAPTER_MACES,
	[11] = ITEM_STYLE_CHAPTER_SHIELDS,
	[12] = ITEM_STYLE_CHAPTER_SHOULDERS,
	[13] = ITEM_STYLE_CHAPTER_STAVES,
	[14] = ITEM_STYLE_CHAPTER_SWORDS,
}

ECO.styles = {
	[ITEMSTYLE_RACIAL_BRETON]  = {stype = AIRG_STYLE_BASIC}, --Breton
	[ITEMSTYLE_RACIAL_REDGUARD]  = {stype = AIRG_STYLE_BASIC}, --Redguard
	[ITEMSTYLE_RACIAL_ORC]  = {stype = AIRG_STYLE_BASIC}, --Orc
	[ITEMSTYLE_RACIAL_DARK_ELF]  = {stype = AIRG_STYLE_BASIC}, --Dark Elf
	[ITEMSTYLE_RACIAL_NORD]  = {stype = AIRG_STYLE_BASIC}, --Nord
	[ITEMSTYLE_RACIAL_ARGONIAN]  = {stype = AIRG_STYLE_BASIC}, --Argonian
	[ITEMSTYLE_RACIAL_HIGH_ELF] =  {stype = AIRG_STYLE_BASIC}, --High Elf
	[ITEMSTYLE_RACIAL_WOOD_ELF]  = {stype = AIRG_STYLE_BASIC}, --Wood Elf
	[ITEMSTYLE_RACIAL_KHAJIIT]  = {stype = AIRG_STYLE_BASIC}, --Khajiit
	[ITEMSTYLE_AREA_ANCIENT_ELF] = {stype = AIRG_STYLE_BASIC}, --Ancient Elf
	[ITEMSTYLE_AREA_REACH] = {stype = AIRG_STYLE_BASIC}, --Reach
	[ITEMSTYLE_ENEMY_PRIMITIVE] = {stype = AIRG_STYLE_BASIC}, --Primitive
	[ITEMSTYLE_ENEMY_DAEDRIC] = {stype = AIRG_STYLE_BASIC}, --Daedric
	[ITEMSTYLE_RACIAL_IMPERIAL] = {stype = AIRG_STYLE_BASIC}, --Imperial
	[ITEMSTYLE_AREA_SOUL_SHRIVEN] = {stype = AIRG_STYLE_BASIC}, --Soul Shriven
	[ITEMSTYLE_AREA_DWEMER] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1144}, --Dwemer
	[ITEMSTYLE_GLASS] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1319}, --Glass
	[ITEMSTYLE_AREA_XIVKYN] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1181}, --Xivkyn
	[ITEMSTYLE_AREA_ANCIENT_ORC] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1341}, --Ancient Orc
	[ITEMSTYLE_AREA_AKAVIRI] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1318}, --Akaviri
	[ITEMSTYLE_UNDAUNTED] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1348}, --Mercenary
	[ITEMSTYLE_DEITY_MALACATH] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1412}, --Malacath
	[ITEMSTYLE_DEITY_TRINIMAC] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1411}, --Trinimac
	[ITEMSTYLE_ORG_OUTLAW] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1417}, --Outlaw
	[ITEMSTYLE_ALLIANCE_EBONHEART] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1414}, --Ebonheart
	[ITEMSTYLE_ALLIANCE_ALDMERI] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1415}, --Aldmeri
	[ITEMSTYLE_ALLIANCE_DAGGERFALL] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1416}, --Daggerfall
	[ITEMSTYLE_ORG_ABAHS_WATCH] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1422}, --Abah's Watch
	[ITEMSTYLE_ORG_THIEVES_GUILD] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1423}, --ThievesGuild
	[ITEMSTYLE_ORG_ASSASSINS] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1424}, --Assassins League
	[ITEMSTYLE_ENEMY_DROMOTHRA] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1659}, --DroMathra
	[ITEMSTYLE_DEITY_AKATOSH] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1660}, --Akatosh
	[ITEMSTYLE_ORG_DARK_BROTHERHOOD] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1661}, --Dark Brotherhood
	[ITEMSTYLE_ENEMY_MINOTAUR] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1662}, --Minotaur
	[ITEMSTYLE_RAIDS_CRAGLORN] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1714}, --Craglorn
	[ITEMSTYLE_ENEMY_DRAUGR] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1715}, --Draugr
	[ITEMSTYLE_AREA_YOKUDAN] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1713}, --Yokudan
	[ITEMSTYLE_HOLIDAY_HOLLOWJACK] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1545}, --Hallowjack
	[ITEMSTYLE_HOLIDAY_SKINCHANGER] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1676}, --Skinchanger
	[ITEMSTYLE_EBONY] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1798}, --Ebony
	[ITEMSTYLE_AREA_RA_GADA] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1797}, --Ra Gada
	[ITEMSTYLE_ENEMY_SILKEN_RING] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1796}, --Silken Ring
	[ITEMSTYLE_ENEMY_MAZZATUN] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1795}, --Mazzatum
	[ITEMSTYLE_HOLIDAY_GRIM_HARLEQUIN] = {stype = AIRG_STYLE_CROWNSTORE}, --Grim Harlequin
	[ITEMSTYLE_HOLIDAY_FROSTCASTER] = {stype = AIRG_STYLE_CROWNSTORE}, --Frostcaster
	[ITEMSTYLE_ORG_MORAG_TONG] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1933}, --Morag Tong
	[ITEMSTYLE_ORG_ORDINATOR] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1935}, --Ordinator
	[ITEMSTYLE_ORG_BUOYANT_ARMIGER] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1934}, --Buoyant Armiger
	[ITEMSTYLE_AREA_ASHLANDER] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 1932}, --Ashlander
	[ITEMSTYLE_ORG_REDORAN] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 2022}, --Redoran
	[ITEMSTYLE_ORG_HLAALU] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 2021}, --Hlaalu
	[ITEMSTYLE_ORG_TELVANNI] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 2023}, --Telvanni
	[61] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 2098, api = 100021}, --Bloodforge
	[62] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 2097, api = 100021}, --Dreadhorn
	[65] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 2044, api = 100021}, --Apostle
	[66] = {stype = AIRG_STYLE_CHAPTERIZED, achiev = 2045, api = 100021}, --Ebonshadow
}


ECO.qualityColours = {
	"FFFFFF", -- Normal
	"1aff1a", -- Fine
	"1a75ff", -- Superior
	"e600e6", -- Epic
	"ffff33"  -- Legendary
}

ECO.qualityNames = {
	"Normal",
	"Fine",
	"Superior",
	"Epic",
	"Legendary"
}